#ifndef HELPERCLASSES_GLOBAL_H
#define HELPERCLASSES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HELPERCLASSES_LIBRARY)
#define HELPERCLASSES_EXPORT Q_DECL_EXPORT
#else
#define HELPERCLASSES_EXPORT Q_DECL_IMPORT
#endif

#endif // HELPERCLASSES_GLOBAL_H
